#ifndef A_DENSE_H
#define A_DENSE_H

#include <libfixed/fixed.h>

__nv fixed a_dense[64][64] = {
	{F_LIT(-4), F_LIT(3),  F_LIT(2),  F_LIT(0),  F_LIT(3),  F_LIT(3),
	 F_LIT(2),  F_LIT(4),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(2),
	 F_LIT(2),  F_LIT(0),  F_LIT(2),  F_LIT(-5), F_LIT(-2), F_LIT(-5),
	 F_LIT(-2), F_LIT(-5), F_LIT(2),  F_LIT(-5), F_LIT(-3), F_LIT(2),
	 F_LIT(0),  F_LIT(-5), F_LIT(-3), F_LIT(-5), F_LIT(0),  F_LIT(-5),
	 F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(2),
	 F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(-2), F_LIT(0),
	 F_LIT(0),  F_LIT(-5), F_LIT(-4), F_LIT(3),  F_LIT(0),  F_LIT(-3),
	 F_LIT(4),  F_LIT(3),  F_LIT(0),  F_LIT(2),  F_LIT(2),  F_LIT(-2),
	 F_LIT(-2), F_LIT(-4), F_LIT(-3), F_LIT(0),  F_LIT(2),  F_LIT(-3),
	 F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(0)},
	{F_LIT(0),  F_LIT(-4), F_LIT(2),  F_LIT(4), F_LIT(3),  F_LIT(3),
	 F_LIT(4),  F_LIT(0),  F_LIT(-2), F_LIT(3), F_LIT(-3), F_LIT(4),
	 F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0), F_LIT(-2), F_LIT(0),
	 F_LIT(0),  F_LIT(3),  F_LIT(-4), F_LIT(0), F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(0), F_LIT(-2), F_LIT(-4),
	 F_LIT(-2), F_LIT(-5), F_LIT(-3), F_LIT(0), F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0), F_LIT(-3), F_LIT(0),
	 F_LIT(4),  F_LIT(3),  F_LIT(0),  F_LIT(4), F_LIT(3),  F_LIT(0),
	 F_LIT(-3), F_LIT(-3), F_LIT(0),  F_LIT(3), F_LIT(4),  F_LIT(2),
	 F_LIT(-2), F_LIT(-2), F_LIT(-3), F_LIT(2), F_LIT(0),  F_LIT(2),
	 F_LIT(2),  F_LIT(-5), F_LIT(-5), F_LIT(-2)},
	{F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(-5), F_LIT(-5),
	 F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-2), F_LIT(-2), F_LIT(-4),
	 F_LIT(-2), F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(-2), F_LIT(3),
	 F_LIT(-4), F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(-4),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(2),  F_LIT(-3),
	 F_LIT(-5), F_LIT(-4), F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(4),
	 F_LIT(0),  F_LIT(-3), F_LIT(3),  F_LIT(2),  F_LIT(0),  F_LIT(0),
	 F_LIT(-4), F_LIT(-4), F_LIT(2),  F_LIT(-4), F_LIT(4),  F_LIT(0),
	 F_LIT(0),  F_LIT(4),  F_LIT(2),  F_LIT(2),  F_LIT(0),  F_LIT(0),
	 F_LIT(-2), F_LIT(-5), F_LIT(-3), F_LIT(-5), F_LIT(-5), F_LIT(0),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(0)},
	{F_LIT(4),  F_LIT(4),  F_LIT(-5), F_LIT(3),  F_LIT(3),  F_LIT(0),
	 F_LIT(2),  F_LIT(2),  F_LIT(2),  F_LIT(3),  F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(-3), F_LIT(4),  F_LIT(4),
	 F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(2),  F_LIT(2),  F_LIT(4),
	 F_LIT(4),  F_LIT(-3), F_LIT(-4), F_LIT(4),  F_LIT(0),  F_LIT(-2),
	 F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(2),  F_LIT(3),  F_LIT(2),
	 F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-4), F_LIT(-5),
	 F_LIT(-3), F_LIT(4),  F_LIT(-4), F_LIT(0)},
	{F_LIT(-3), F_LIT(-5), F_LIT(4),  F_LIT(3),  F_LIT(3),  F_LIT(-3),
	 F_LIT(-5), F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(2),
	 F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(0),
	 F_LIT(-2), F_LIT(-5), F_LIT(0),  F_LIT(3),  F_LIT(-4), F_LIT(-5),
	 F_LIT(-2), F_LIT(-4), F_LIT(3),  F_LIT(0),  F_LIT(-5), F_LIT(-2),
	 F_LIT(-5), F_LIT(-3), F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(-3),
	 F_LIT(0),  F_LIT(4),  F_LIT(-3), F_LIT(-3), F_LIT(-5), F_LIT(0),
	 F_LIT(-5), F_LIT(-5), F_LIT(4),  F_LIT(2),  F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(-3), F_LIT(0),  F_LIT(-2), F_LIT(2),  F_LIT(0),
	 F_LIT(-5), F_LIT(3),  F_LIT(0),  F_LIT(-5), F_LIT(-5), F_LIT(0),
	 F_LIT(-5), F_LIT(-5), F_LIT(-2), F_LIT(4)},
	{F_LIT(0),  F_LIT(3),  F_LIT(-2), F_LIT(2),  F_LIT(-2), F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(-5), F_LIT(-3),
	 F_LIT(-5), F_LIT(4),  F_LIT(-5), F_LIT(2),  F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(-4), F_LIT(-3), F_LIT(-4), F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(-4), F_LIT(3),  F_LIT(2),  F_LIT(4),  F_LIT(-2),
	 F_LIT(3),  F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(4),
	 F_LIT(-4), F_LIT(-5), F_LIT(-4), F_LIT(3),  F_LIT(-2), F_LIT(0),
	 F_LIT(2),  F_LIT(-5), F_LIT(0),  F_LIT(-3), F_LIT(-4), F_LIT(0),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(0),
	 F_LIT(4),  F_LIT(-4), F_LIT(-2), F_LIT(-4), F_LIT(2),  F_LIT(3),
	 F_LIT(0),  F_LIT(4),  F_LIT(2),  F_LIT(-4)},
	{F_LIT(-2), F_LIT(-4), F_LIT(-2), F_LIT(-2), F_LIT(0), F_LIT(-4),
	 F_LIT(4),  F_LIT(-3), F_LIT(-2), F_LIT(4),  F_LIT(2), F_LIT(-5),
	 F_LIT(-5), F_LIT(0),  F_LIT(2),  F_LIT(-5), F_LIT(0), F_LIT(-3),
	 F_LIT(0),  F_LIT(-4), F_LIT(-5), F_LIT(4),  F_LIT(4), F_LIT(-5),
	 F_LIT(-2), F_LIT(-4), F_LIT(2),  F_LIT(2),  F_LIT(0), F_LIT(2),
	 F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(2),  F_LIT(3), F_LIT(0),
	 F_LIT(-2), F_LIT(-4), F_LIT(3),  F_LIT(-3), F_LIT(0), F_LIT(4),
	 F_LIT(2),  F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(3), F_LIT(4),
	 F_LIT(-2), F_LIT(-2), F_LIT(0),  F_LIT(-5), F_LIT(0), F_LIT(-2),
	 F_LIT(3),  F_LIT(2),  F_LIT(-2), F_LIT(-3), F_LIT(2), F_LIT(-5),
	 F_LIT(-3), F_LIT(-2), F_LIT(-2), F_LIT(0)},
	{F_LIT(4),  F_LIT(3),  F_LIT(0),  F_LIT(4),  F_LIT(4),  F_LIT(3),
	 F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(-5),
	 F_LIT(-3), F_LIT(2),  F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(3),
	 F_LIT(-3), F_LIT(0),  F_LIT(2),  F_LIT(-3), F_LIT(-5), F_LIT(3),
	 F_LIT(2),  F_LIT(-2), F_LIT(-3), F_LIT(0),  F_LIT(4),  F_LIT(2),
	 F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(4),
	 F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(4),  F_LIT(-2), F_LIT(-4),
	 F_LIT(2),  F_LIT(3),  F_LIT(-3), F_LIT(0),  F_LIT(-3), F_LIT(-2),
	 F_LIT(0),  F_LIT(-2), F_LIT(2),  F_LIT(3),  F_LIT(-2), F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(-4), F_LIT(4),  F_LIT(-3),
	 F_LIT(4),  F_LIT(-2), F_LIT(3),  F_LIT(4)},
	{F_LIT(-2), F_LIT(-3), F_LIT(0),  F_LIT(3),  F_LIT(-4), F_LIT(4),
	 F_LIT(0),  F_LIT(4),  F_LIT(-2), F_LIT(2),  F_LIT(3),  F_LIT(4),
	 F_LIT(0),  F_LIT(3),  F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(2),
	 F_LIT(-2), F_LIT(-5), F_LIT(-5), F_LIT(-4), F_LIT(-5), F_LIT(-3),
	 F_LIT(0),  F_LIT(4),  F_LIT(-3), F_LIT(3),  F_LIT(0),  F_LIT(4),
	 F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(3),
	 F_LIT(4),  F_LIT(4),  F_LIT(4),  F_LIT(3),  F_LIT(4),  F_LIT(-4),
	 F_LIT(-5), F_LIT(-4), F_LIT(2),  F_LIT(0),  F_LIT(-3), F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(-2), F_LIT(-5),
	 F_LIT(2),  F_LIT(-3), F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(2),
	 F_LIT(4),  F_LIT(0),  F_LIT(2),  F_LIT(-2)},
	{F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(-5),
	 F_LIT(-4), F_LIT(-5), F_LIT(-2), F_LIT(4),  F_LIT(0),  F_LIT(4),
	 F_LIT(-3), F_LIT(-3), F_LIT(-5), F_LIT(0),  F_LIT(2),  F_LIT(-3),
	 F_LIT(0),  F_LIT(3),  F_LIT(-4), F_LIT(-4), F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(3),  F_LIT(-5), F_LIT(-3), F_LIT(4),  F_LIT(3),
	 F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(2),  F_LIT(-3), F_LIT(3),
	 F_LIT(0),  F_LIT(4),  F_LIT(-5), F_LIT(3),  F_LIT(-3), F_LIT(4),
	 F_LIT(4),  F_LIT(-3), F_LIT(-3), F_LIT(2),  F_LIT(-2), F_LIT(0),
	 F_LIT(0),  F_LIT(-4), F_LIT(-4), F_LIT(-4), F_LIT(2),  F_LIT(0),
	 F_LIT(0),  F_LIT(4),  F_LIT(-3), F_LIT(3),  F_LIT(0),  F_LIT(2),
	 F_LIT(3),  F_LIT(-2), F_LIT(4),  F_LIT(3)},
	{F_LIT(-4), F_LIT(3),  F_LIT(0),  F_LIT(2),  F_LIT(2),  F_LIT(0),
	 F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(3),  F_LIT(-3), F_LIT(-4),
	 F_LIT(2),  F_LIT(4),  F_LIT(0),  F_LIT(2),  F_LIT(-4), F_LIT(0),
	 F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(2),  F_LIT(3),  F_LIT(-4),
	 F_LIT(2),  F_LIT(3),  F_LIT(0),  F_LIT(-3), F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(-3),
	 F_LIT(3),  F_LIT(2),  F_LIT(-5), F_LIT(-4), F_LIT(0),  F_LIT(-5),
	 F_LIT(-5), F_LIT(-4), F_LIT(-5), F_LIT(-4), F_LIT(4),  F_LIT(-5),
	 F_LIT(2),  F_LIT(0),  F_LIT(-5), F_LIT(-4), F_LIT(4),  F_LIT(-5),
	 F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(-4), F_LIT(3),  F_LIT(0),
	 F_LIT(-3), F_LIT(-3), F_LIT(3),  F_LIT(2)},
	{F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-2), F_LIT(-4), F_LIT(-4), F_LIT(2),  F_LIT(-4), F_LIT(2),
	 F_LIT(-3), F_LIT(0),  F_LIT(2),  F_LIT(3),  F_LIT(-2), F_LIT(-4),
	 F_LIT(-2), F_LIT(-4), F_LIT(-2), F_LIT(0),  F_LIT(4),  F_LIT(-3),
	 F_LIT(3),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-3),
	 F_LIT(2),  F_LIT(-3), F_LIT(4),  F_LIT(4),  F_LIT(-3), F_LIT(2),
	 F_LIT(3),  F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(4),
	 F_LIT(-4), F_LIT(2),  F_LIT(-2), F_LIT(-4), F_LIT(0),  F_LIT(0),
	 F_LIT(-3), F_LIT(-4), F_LIT(-5), F_LIT(0),  F_LIT(-5), F_LIT(-5),
	 F_LIT(4),  F_LIT(-2), F_LIT(-5), F_LIT(0),  F_LIT(-3), F_LIT(-4),
	 F_LIT(0),  F_LIT(2),  F_LIT(3),  F_LIT(0)},
	{F_LIT(0),  F_LIT(-5), F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(-5),
	 F_LIT(-4), F_LIT(3),  F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(0),
	 F_LIT(2),  F_LIT(-2), F_LIT(-4), F_LIT(4),  F_LIT(4),  F_LIT(4),
	 F_LIT(-5), F_LIT(3),  F_LIT(-2), F_LIT(-4), F_LIT(3),  F_LIT(3),
	 F_LIT(-5), F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-5),
	 F_LIT(0),  F_LIT(-4), F_LIT(2),  F_LIT(2),  F_LIT(4),  F_LIT(-3),
	 F_LIT(-2), F_LIT(-4), F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(-5),
	 F_LIT(3),  F_LIT(2),  F_LIT(-5), F_LIT(-2), F_LIT(-3), F_LIT(0),
	 F_LIT(2),  F_LIT(4),  F_LIT(3),  F_LIT(-2), F_LIT(-4), F_LIT(0),
	 F_LIT(-4), F_LIT(-4), F_LIT(-5), F_LIT(-4)},
	{F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(-4), F_LIT(-3),
	 F_LIT(-3), F_LIT(2),  F_LIT(-4), F_LIT(-3), F_LIT(-2), F_LIT(-5),
	 F_LIT(-3), F_LIT(-5), F_LIT(-2), F_LIT(-4), F_LIT(0),  F_LIT(-4),
	 F_LIT(-2), F_LIT(-4), F_LIT(0),  F_LIT(-4), F_LIT(-5), F_LIT(-3),
	 F_LIT(-4), F_LIT(-5), F_LIT(2),  F_LIT(0),  F_LIT(-4), F_LIT(0),
	 F_LIT(-3), F_LIT(3),  F_LIT(2),  F_LIT(3),  F_LIT(-2), F_LIT(0),
	 F_LIT(-4), F_LIT(3),  F_LIT(2),  F_LIT(-4), F_LIT(-4), F_LIT(2),
	 F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(2),  F_LIT(-2),
	 F_LIT(-2), F_LIT(0),  F_LIT(-5), F_LIT(3),  F_LIT(-2), F_LIT(4),
	 F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(-2),
	 F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(3)},
	{F_LIT(4),  F_LIT(-3), F_LIT(3),  F_LIT(-2), F_LIT(3),  F_LIT(-2),
	 F_LIT(-5), F_LIT(-5), F_LIT(3),  F_LIT(0),  F_LIT(-2), F_LIT(0),
	 F_LIT(-5), F_LIT(-2), F_LIT(0),  F_LIT(2),  F_LIT(4),  F_LIT(3),
	 F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(-3), F_LIT(-5), F_LIT(-3),
	 F_LIT(0),  F_LIT(-5), F_LIT(-2), F_LIT(2),  F_LIT(2),  F_LIT(-4),
	 F_LIT(4),  F_LIT(-2), F_LIT(0),  F_LIT(4),  F_LIT(4),  F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(3),  F_LIT(0),  F_LIT(-5),
	 F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(-3), F_LIT(-2), F_LIT(-4),
	 F_LIT(-3), F_LIT(-5), F_LIT(2),  F_LIT(0),  F_LIT(3),  F_LIT(-2),
	 F_LIT(-5), F_LIT(-4), F_LIT(-5), F_LIT(-4), F_LIT(2),  F_LIT(0),
	 F_LIT(2),  F_LIT(2),  F_LIT(2),  F_LIT(0)},
	{F_LIT(-4), F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-3), F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(-2), F_LIT(4),
	 F_LIT(2),  F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(3),
	 F_LIT(-3), F_LIT(-2), F_LIT(-4), F_LIT(2),  F_LIT(-2), F_LIT(0),
	 F_LIT(0),  F_LIT(-2), F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-3), F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(-5), F_LIT(-5),
	 F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(-5), F_LIT(3),  F_LIT(2),  F_LIT(0),  F_LIT(0),
	 F_LIT(2),  F_LIT(-3), F_LIT(4),  F_LIT(-2), F_LIT(-2), F_LIT(-2),
	 F_LIT(-2), F_LIT(-3), F_LIT(-3), F_LIT(0)},
	{F_LIT(0),  F_LIT(2),  F_LIT(4),  F_LIT(3),  F_LIT(0),  F_LIT(-2),
	 F_LIT(4),  F_LIT(3),  F_LIT(-3), F_LIT(3),  F_LIT(-4), F_LIT(0),
	 F_LIT(-5), F_LIT(-5), F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(-3),
	 F_LIT(-4), F_LIT(0),  F_LIT(4),  F_LIT(3),  F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(3),  F_LIT(3),  F_LIT(-5), F_LIT(0),  F_LIT(0),
	 F_LIT(3),  F_LIT(0),  F_LIT(-5), F_LIT(3),  F_LIT(0),  F_LIT(3),
	 F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(-2), F_LIT(0),
	 F_LIT(2),  F_LIT(2),  F_LIT(-5), F_LIT(0),  F_LIT(-2), F_LIT(4),
	 F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-4),
	 F_LIT(-2), F_LIT(0),  F_LIT(-3), F_LIT(3),  F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(4)},
	{F_LIT(3),  F_LIT(-2), F_LIT(0),  F_LIT(-4), F_LIT(3), F_LIT(0),
	 F_LIT(4),  F_LIT(-5), F_LIT(3),  F_LIT(4),  F_LIT(0), F_LIT(-5),
	 F_LIT(-3), F_LIT(-2), F_LIT(4),  F_LIT(0),  F_LIT(4), F_LIT(-3),
	 F_LIT(0),  F_LIT(-5), F_LIT(-5), F_LIT(-2), F_LIT(3), F_LIT(0),
	 F_LIT(-5), F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(4), F_LIT(4),
	 F_LIT(2),  F_LIT(-2), F_LIT(2),  F_LIT(2),  F_LIT(4), F_LIT(3),
	 F_LIT(0),  F_LIT(2),  F_LIT(2),  F_LIT(3),  F_LIT(0), F_LIT(0),
	 F_LIT(-5), F_LIT(-4), F_LIT(-4), F_LIT(-4), F_LIT(4), F_LIT(0),
	 F_LIT(0),  F_LIT(-5), F_LIT(-2), F_LIT(0),  F_LIT(0), F_LIT(-3),
	 F_LIT(2),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(4), F_LIT(-3),
	 F_LIT(2),  F_LIT(0),  F_LIT(4),  F_LIT(3)},
	{F_LIT(4),  F_LIT(3),  F_LIT(0),  F_LIT(-5), F_LIT(-2), F_LIT(-4),
	 F_LIT(3),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(-4),
	 F_LIT(-4), F_LIT(-3), F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(-3), F_LIT(-3), F_LIT(-4), F_LIT(3),
	 F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(4),
	 F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(3),  F_LIT(3),  F_LIT(0),
	 F_LIT(-5), F_LIT(3),  F_LIT(-2), F_LIT(0),  F_LIT(3),  F_LIT(0),
	 F_LIT(3),  F_LIT(0),  F_LIT(-2), F_LIT(-2), F_LIT(0),  F_LIT(0),
	 F_LIT(4),  F_LIT(-3), F_LIT(0),  F_LIT(4),  F_LIT(-3), F_LIT(4),
	 F_LIT(2),  F_LIT(3),  F_LIT(-5), F_LIT(4),  F_LIT(-3), F_LIT(0),
	 F_LIT(3),  F_LIT(3),  F_LIT(3),  F_LIT(3)},
	{F_LIT(3),  F_LIT(-3), F_LIT(4),  F_LIT(-2), F_LIT(0),  F_LIT(4),
	 F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(4),  F_LIT(-5), F_LIT(4),
	 F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(-3), F_LIT(-5), F_LIT(0),
	 F_LIT(-5), F_LIT(-3), F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(2),
	 F_LIT(-5), F_LIT(-2), F_LIT(4),  F_LIT(0),  F_LIT(-3), F_LIT(4),
	 F_LIT(-3), F_LIT(4),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(3),
	 F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(-3), F_LIT(3),
	 F_LIT(-2), F_LIT(4),  F_LIT(-2), F_LIT(-5), F_LIT(4),  F_LIT(-5),
	 F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-2), F_LIT(-2), F_LIT(-2),
	 F_LIT(0),  F_LIT(-4), F_LIT(2),  F_LIT(-3), F_LIT(3),  F_LIT(4),
	 F_LIT(4),  F_LIT(-2), F_LIT(-5), F_LIT(3)},
	{F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(2),  F_LIT(-3), F_LIT(4),  F_LIT(4),  F_LIT(3),
	 F_LIT(-4), F_LIT(-3), F_LIT(-3), F_LIT(2),  F_LIT(-4), F_LIT(3),
	 F_LIT(-4), F_LIT(2),  F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(-5),
	 F_LIT(-2), F_LIT(-2), F_LIT(-4), F_LIT(-5), F_LIT(3),  F_LIT(2),
	 F_LIT(3),  F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(-4), F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(4),
	 F_LIT(-5), F_LIT(-2), F_LIT(-3), F_LIT(-4), F_LIT(-5), F_LIT(0),
	 F_LIT(-4), F_LIT(2),  F_LIT(0),  F_LIT(-3), F_LIT(2),  F_LIT(3),
	 F_LIT(-3), F_LIT(0),  F_LIT(-3), F_LIT(-4), F_LIT(4),  F_LIT(-3),
	 F_LIT(-4), F_LIT(-2), F_LIT(0),  F_LIT(0)},
	{F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(2), F_LIT(0),  F_LIT(-5), F_LIT(0),
	 F_LIT(-5), F_LIT(4),  F_LIT(-5), F_LIT(4), F_LIT(-3), F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(-5), F_LIT(-3), F_LIT(4), F_LIT(2),  F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(3), F_LIT(2),  F_LIT(-2), F_LIT(-3),
	 F_LIT(-4), F_LIT(-3), F_LIT(2),  F_LIT(0), F_LIT(-2), F_LIT(0),  F_LIT(3),
	 F_LIT(-3), F_LIT(2),  F_LIT(2),  F_LIT(3), F_LIT(-2), F_LIT(3),  F_LIT(2),
	 F_LIT(-3), F_LIT(3),  F_LIT(3),  F_LIT(0), F_LIT(3),  F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(2),  F_LIT(-3), F_LIT(0), F_LIT(2),  F_LIT(2),  F_LIT(0),
	 F_LIT(0),  F_LIT(3),  F_LIT(-5), F_LIT(3), F_LIT(-2), F_LIT(0),  F_LIT(4),
	 F_LIT(-3)},
	{F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-2), F_LIT(3),
	 F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(-4),
	 F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(-5), F_LIT(0),
	 F_LIT(-4), F_LIT(-3), F_LIT(-4), F_LIT(3),  F_LIT(0),  F_LIT(4),
	 F_LIT(-5), F_LIT(-3), F_LIT(4),  F_LIT(3),  F_LIT(-2), F_LIT(-3),
	 F_LIT(-5), F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-4),
	 F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(2),  F_LIT(-5), F_LIT(-4), F_LIT(0),  F_LIT(-3),
	 F_LIT(-5), F_LIT(2),  F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(0),
	 F_LIT(-5), F_LIT(-3), F_LIT(4),  F_LIT(0),  F_LIT(2),  F_LIT(-5),
	 F_LIT(3),  F_LIT(-2), F_LIT(-5), F_LIT(-5)},
	{F_LIT(-2), F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-3), F_LIT(0),  F_LIT(-4), F_LIT(2),  F_LIT(0),  F_LIT(-2),
	 F_LIT(4),  F_LIT(-5), F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(2),
	 F_LIT(4),  F_LIT(-3), F_LIT(0),  F_LIT(-4), F_LIT(-2), F_LIT(4),
	 F_LIT(-5), F_LIT(-2), F_LIT(0),  F_LIT(-2), F_LIT(-2), F_LIT(0),
	 F_LIT(-5), F_LIT(2),  F_LIT(2),  F_LIT(0),  F_LIT(-2), F_LIT(0),
	 F_LIT(-2), F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(3),  F_LIT(-2),
	 F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(3),  F_LIT(-4), F_LIT(3),
	 F_LIT(-4), F_LIT(4),  F_LIT(3),  F_LIT(-4), F_LIT(-2), F_LIT(-5),
	 F_LIT(4),  F_LIT(-5), F_LIT(2),  F_LIT(4),  F_LIT(-2), F_LIT(-4),
	 F_LIT(4),  F_LIT(2),  F_LIT(4),  F_LIT(-4)},
	{F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(4),  F_LIT(-3), F_LIT(-5),
	 F_LIT(-4), F_LIT(0),  F_LIT(-4), F_LIT(-3), F_LIT(-4), F_LIT(-5),
	 F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(-2), F_LIT(3),
	 F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(3),  F_LIT(-5), F_LIT(-2),
	 F_LIT(-4), F_LIT(0),  F_LIT(-5), F_LIT(4),  F_LIT(3),  F_LIT(3),
	 F_LIT(0),  F_LIT(-4), F_LIT(-4), F_LIT(2),  F_LIT(0),  F_LIT(-5),
	 F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(-2),
	 F_LIT(-4), F_LIT(-3), F_LIT(0),  F_LIT(-4), F_LIT(-2), F_LIT(-5),
	 F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-3), F_LIT(-4),
	 F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(-3)},
	{F_LIT(0),  F_LIT(4),  F_LIT(2),  F_LIT(-3), F_LIT(-2), F_LIT(-4),
	 F_LIT(-5), F_LIT(-4), F_LIT(0),  F_LIT(-2), F_LIT(3),  F_LIT(-5),
	 F_LIT(4),  F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(-3), F_LIT(3),
	 F_LIT(-5), F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(-3),
	 F_LIT(0),  F_LIT(-2), F_LIT(-5), F_LIT(-2), F_LIT(0),  F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(-3), F_LIT(3),  F_LIT(2),  F_LIT(2),
	 F_LIT(-2), F_LIT(2),  F_LIT(-2), F_LIT(2),  F_LIT(-2), F_LIT(4),
	 F_LIT(-3), F_LIT(-2), F_LIT(-2), F_LIT(4),  F_LIT(2),  F_LIT(-4),
	 F_LIT(0),  F_LIT(3),  F_LIT(-2), F_LIT(-3), F_LIT(-4), F_LIT(0),
	 F_LIT(4),  F_LIT(-4), F_LIT(-2), F_LIT(-2), F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(-5), F_LIT(-3), F_LIT(0)},
	{F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(-2), F_LIT(-4),
	 F_LIT(-2), F_LIT(-5), F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(-5), F_LIT(3),  F_LIT(3),  F_LIT(4),  F_LIT(-4),
	 F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-4), F_LIT(-4), F_LIT(-3),
	 F_LIT(-5), F_LIT(4),  F_LIT(3),  F_LIT(4),  F_LIT(0),  F_LIT(-4),
	 F_LIT(0),  F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(4),  F_LIT(0),
	 F_LIT(-3), F_LIT(0),  F_LIT(4),  F_LIT(-5), F_LIT(4),  F_LIT(0),
	 F_LIT(2),  F_LIT(4),  F_LIT(2),  F_LIT(0),  F_LIT(-5), F_LIT(-3),
	 F_LIT(-2), F_LIT(4),  F_LIT(-4), F_LIT(-4), F_LIT(-5), F_LIT(-3),
	 F_LIT(3),  F_LIT(-4), F_LIT(0),  F_LIT(3),  F_LIT(2),  F_LIT(-3),
	 F_LIT(0),  F_LIT(4),  F_LIT(-3), F_LIT(0)},
	{F_LIT(2),  F_LIT(3),  F_LIT(2),  F_LIT(-5), F_LIT(4),  F_LIT(0),
	 F_LIT(0),  F_LIT(4),  F_LIT(4),  F_LIT(-5), F_LIT(-2), F_LIT(2),
	 F_LIT(-3), F_LIT(4),  F_LIT(0),  F_LIT(3),  F_LIT(4),  F_LIT(-4),
	 F_LIT(2),  F_LIT(-2), F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(-3),
	 F_LIT(-3), F_LIT(2),  F_LIT(-2), F_LIT(-4), F_LIT(-5), F_LIT(-5),
	 F_LIT(0),  F_LIT(-5), F_LIT(4),  F_LIT(0),  F_LIT(3),  F_LIT(4),
	 F_LIT(-5), F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-2),
	 F_LIT(2),  F_LIT(-3), F_LIT(4),  F_LIT(2),  F_LIT(-2), F_LIT(-3),
	 F_LIT(-2), F_LIT(2),  F_LIT(-2), F_LIT(4),  F_LIT(0),  F_LIT(0),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-2), F_LIT(0),  F_LIT(-5), F_LIT(0)},
	{F_LIT(-4), F_LIT(-2), F_LIT(0),  F_LIT(3),  F_LIT(-3), F_LIT(2),
	 F_LIT(-5), F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(-2),
	 F_LIT(4),  F_LIT(-3), F_LIT(0),  F_LIT(-2), F_LIT(-4), F_LIT(-2),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(0),
	 F_LIT(-4), F_LIT(-4), F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(2),
	 F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(3),
	 F_LIT(0),  F_LIT(4),  F_LIT(2),  F_LIT(3),  F_LIT(0),  F_LIT(-3),
	 F_LIT(0),  F_LIT(-4), F_LIT(-2), F_LIT(-4), F_LIT(-2), F_LIT(-2),
	 F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(4),  F_LIT(0),  F_LIT(0),
	 F_LIT(-4), F_LIT(-3), F_LIT(-4), F_LIT(-3), F_LIT(4),  F_LIT(2),
	 F_LIT(0),  F_LIT(-5), F_LIT(3),  F_LIT(0)},
	{F_LIT(-2), F_LIT(3),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(-2), F_LIT(2),  F_LIT(0),  F_LIT(2),  F_LIT(4),
	 F_LIT(-2), F_LIT(-4), F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(2),
	 F_LIT(-4), F_LIT(2),  F_LIT(-5), F_LIT(-5), F_LIT(0),  F_LIT(-4),
	 F_LIT(2),  F_LIT(3),  F_LIT(-3), F_LIT(0),  F_LIT(-5), F_LIT(2),
	 F_LIT(-5), F_LIT(4),  F_LIT(0),  F_LIT(-2), F_LIT(4),  F_LIT(0),
	 F_LIT(3),  F_LIT(-2), F_LIT(-3), F_LIT(-5), F_LIT(-4), F_LIT(3),
	 F_LIT(-2), F_LIT(0),  F_LIT(-5), F_LIT(3),  F_LIT(0),  F_LIT(4),
	 F_LIT(-4), F_LIT(3),  F_LIT(-4), F_LIT(0),  F_LIT(4),  F_LIT(-5),
	 F_LIT(4),  F_LIT(3),  F_LIT(0),  F_LIT(2)},
	{F_LIT(4),  F_LIT(2),  F_LIT(-4), F_LIT(0),  F_LIT(3),  F_LIT(-2),
	 F_LIT(-5), F_LIT(-2), F_LIT(-5), F_LIT(3),  F_LIT(-4), F_LIT(-2),
	 F_LIT(2),  F_LIT(-4), F_LIT(3),  F_LIT(2),  F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(-5), F_LIT(2),  F_LIT(-2), F_LIT(3),  F_LIT(3),
	 F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(0),
	 F_LIT(4),  F_LIT(-5), F_LIT(-3), F_LIT(3),  F_LIT(0),  F_LIT(3),
	 F_LIT(-4), F_LIT(0),  F_LIT(-4), F_LIT(-3), F_LIT(0),  F_LIT(4),
	 F_LIT(0),  F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(3),  F_LIT(-3),
	 F_LIT(-2), F_LIT(-4), F_LIT(-4), F_LIT(-3), F_LIT(4),  F_LIT(-5),
	 F_LIT(0),  F_LIT(-2), F_LIT(-5), F_LIT(2),  F_LIT(-3), F_LIT(-2),
	 F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-5)},
	{F_LIT(-2), F_LIT(0),  F_LIT(3),  F_LIT(-2), F_LIT(-5), F_LIT(0),
	 F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(3),  F_LIT(-4), F_LIT(2),
	 F_LIT(0),  F_LIT(4),  F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(-5), F_LIT(-3), F_LIT(-4), F_LIT(-3), F_LIT(0),
	 F_LIT(-5), F_LIT(-2), F_LIT(2),  F_LIT(-2), F_LIT(-2), F_LIT(-3),
	 F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(4),
	 F_LIT(0),  F_LIT(-3), F_LIT(3),  F_LIT(2),  F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(4),  F_LIT(-3), F_LIT(0),  F_LIT(-3), F_LIT(2),
	 F_LIT(0),  F_LIT(-5), F_LIT(3),  F_LIT(-2), F_LIT(3),  F_LIT(0),
	 F_LIT(-4), F_LIT(4),  F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(-2),
	 F_LIT(3),  F_LIT(4),  F_LIT(4),  F_LIT(3)},
	{F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(0),
	 F_LIT(2),  F_LIT(-4), F_LIT(0),  F_LIT(3),  F_LIT(4),  F_LIT(3),
	 F_LIT(4),  F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(4),  F_LIT(3),
	 F_LIT(0),  F_LIT(3),  F_LIT(2),  F_LIT(-5), F_LIT(0),  F_LIT(-2),
	 F_LIT(-3), F_LIT(3),  F_LIT(2),  F_LIT(-2), F_LIT(-2), F_LIT(-2),
	 F_LIT(-3), F_LIT(3),  F_LIT(-2), F_LIT(-2), F_LIT(-4), F_LIT(2),
	 F_LIT(2),  F_LIT(2),  F_LIT(-4), F_LIT(4),  F_LIT(-5), F_LIT(-5),
	 F_LIT(-3), F_LIT(-5), F_LIT(0),  F_LIT(-3), F_LIT(-5), F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(-5), F_LIT(4),  F_LIT(3),  F_LIT(3),
	 F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(3),  F_LIT(-5), F_LIT(2),
	 F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(3)},
	{F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(-2), F_LIT(-5),
	 F_LIT(-2), F_LIT(0),  F_LIT(3),  F_LIT(4),  F_LIT(-5), F_LIT(2),
	 F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(-2), F_LIT(-4),
	 F_LIT(-3), F_LIT(-3), F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(-2),
	 F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(-2), F_LIT(-2), F_LIT(-2),
	 F_LIT(-5), F_LIT(2),  F_LIT(-4), F_LIT(3),  F_LIT(-2), F_LIT(-2),
	 F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(3),
	 F_LIT(-3), F_LIT(2),  F_LIT(0),  F_LIT(-2), F_LIT(2),  F_LIT(-3),
	 F_LIT(2),  F_LIT(3),  F_LIT(4),  F_LIT(-3), F_LIT(0),  F_LIT(-4),
	 F_LIT(-2), F_LIT(-5), F_LIT(-3), F_LIT(-5), F_LIT(-3), F_LIT(2),
	 F_LIT(-2), F_LIT(2),  F_LIT(4),  F_LIT(0)},
	{F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(2),  F_LIT(0),  F_LIT(0),
	 F_LIT(-3), F_LIT(-5), F_LIT(-4), F_LIT(-3), F_LIT(0),  F_LIT(-2),
	 F_LIT(4),  F_LIT(3),  F_LIT(2),  F_LIT(0),  F_LIT(-2), F_LIT(3),
	 F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(3),  F_LIT(-3), F_LIT(4),
	 F_LIT(3),  F_LIT(3),  F_LIT(4),  F_LIT(-5), F_LIT(4),  F_LIT(3),
	 F_LIT(-2), F_LIT(4),  F_LIT(3),  F_LIT(-3), F_LIT(-4), F_LIT(-4),
	 F_LIT(-3), F_LIT(3),  F_LIT(2),  F_LIT(3),  F_LIT(-2), F_LIT(0),
	 F_LIT(-4), F_LIT(2),  F_LIT(4),  F_LIT(3),  F_LIT(-4), F_LIT(4),
	 F_LIT(0),  F_LIT(0),  F_LIT(3),  F_LIT(2),  F_LIT(3),  F_LIT(-4),
	 F_LIT(0),  F_LIT(-3), F_LIT(2),  F_LIT(0),  F_LIT(-5), F_LIT(-5),
	 F_LIT(3),  F_LIT(-5), F_LIT(-4), F_LIT(0)},
	{F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-3),
	 F_LIT(0),  F_LIT(-2), F_LIT(-3), F_LIT(0),  F_LIT(2),  F_LIT(0),
	 F_LIT(-5), F_LIT(4),  F_LIT(-4), F_LIT(0),  F_LIT(3),  F_LIT(4),
	 F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(-5),
	 F_LIT(4),  F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(3),  F_LIT(0),
	 F_LIT(2),  F_LIT(3),  F_LIT(2),  F_LIT(2),  F_LIT(-4), F_LIT(0),
	 F_LIT(0),  F_LIT(-3), F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(4),  F_LIT(3),  F_LIT(-5), F_LIT(-4), F_LIT(4),  F_LIT(4),
	 F_LIT(4),  F_LIT(2),  F_LIT(-5), F_LIT(4),  F_LIT(2),  F_LIT(2),
	 F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(-4),
	 F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(0)},
	{F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(-5),
	 F_LIT(-2), F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(-2),
	 F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(-2), F_LIT(-5), F_LIT(0),
	 F_LIT(-3), F_LIT(3),  F_LIT(3),  F_LIT(-5), F_LIT(-2), F_LIT(-3),
	 F_LIT(-4), F_LIT(-3), F_LIT(-5), F_LIT(4),  F_LIT(4),  F_LIT(-3),
	 F_LIT(0),  F_LIT(-3), F_LIT(2),  F_LIT(-3), F_LIT(-5), F_LIT(3),
	 F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(-5), F_LIT(4),  F_LIT(0),
	 F_LIT(-5), F_LIT(2),  F_LIT(-2), F_LIT(3),  F_LIT(-4), F_LIT(4),
	 F_LIT(3),  F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-3),
	 F_LIT(-3), F_LIT(3),  F_LIT(-3), F_LIT(-5), F_LIT(4),  F_LIT(0),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(0)},
	{F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(2),
	 F_LIT(-3), F_LIT(-4), F_LIT(2),  F_LIT(2),  F_LIT(4),  F_LIT(-3),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(4),
	 F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(2),
	 F_LIT(-5), F_LIT(0),  F_LIT(3),  F_LIT(-4), F_LIT(-2), F_LIT(-2),
	 F_LIT(-3), F_LIT(-5), F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(-4),
	 F_LIT(-2), F_LIT(-3), F_LIT(-3), F_LIT(0),  F_LIT(-4), F_LIT(-3),
	 F_LIT(3),  F_LIT(3),  F_LIT(0),  F_LIT(2),  F_LIT(4),  F_LIT(4),
	 F_LIT(3),  F_LIT(3),  F_LIT(0),  F_LIT(4),  F_LIT(4),  F_LIT(0),
	 F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(-2), F_LIT(-2), F_LIT(-2),
	 F_LIT(-3), F_LIT(0),  F_LIT(2),  F_LIT(-5)},
	{F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(4),  F_LIT(-2), F_LIT(0),
	 F_LIT(0),  F_LIT(-2), F_LIT(-2), F_LIT(-2), F_LIT(4),  F_LIT(2),
	 F_LIT(2),  F_LIT(-2), F_LIT(-4), F_LIT(4),  F_LIT(-5), F_LIT(-4),
	 F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(3),  F_LIT(0),  F_LIT(-3),
	 F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(3),  F_LIT(2),  F_LIT(-4),
	 F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(-5), F_LIT(-3),
	 F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(4),  F_LIT(3),
	 F_LIT(3),  F_LIT(-4), F_LIT(4),  F_LIT(2),  F_LIT(3),  F_LIT(-2),
	 F_LIT(0),  F_LIT(-4), F_LIT(-4), F_LIT(4),  F_LIT(-2), F_LIT(0),
	 F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(-3), F_LIT(-4),
	 F_LIT(-2), F_LIT(-2), F_LIT(-3), F_LIT(-3)},
	{F_LIT(3),  F_LIT(0),  F_LIT(4),  F_LIT(-2), F_LIT(-2), F_LIT(0),
	 F_LIT(-2), F_LIT(-2), F_LIT(0),  F_LIT(-5), F_LIT(-3), F_LIT(0),
	 F_LIT(4),  F_LIT(3),  F_LIT(-5), F_LIT(-5), F_LIT(0),  F_LIT(-4),
	 F_LIT(0),  F_LIT(-5), F_LIT(-2), F_LIT(-5), F_LIT(2),  F_LIT(0),
	 F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(0),
	 F_LIT(3),  F_LIT(2),  F_LIT(-2), F_LIT(-3), F_LIT(2),  F_LIT(0),
	 F_LIT(-2), F_LIT(4),  F_LIT(2),  F_LIT(3),  F_LIT(4),  F_LIT(0),
	 F_LIT(-2), F_LIT(4),  F_LIT(-5), F_LIT(3),  F_LIT(2),  F_LIT(-5),
	 F_LIT(-3), F_LIT(3),  F_LIT(3),  F_LIT(-3), F_LIT(0),  F_LIT(-2),
	 F_LIT(-4), F_LIT(0),  F_LIT(-4), F_LIT(4),  F_LIT(3),  F_LIT(-2),
	 F_LIT(-5), F_LIT(-2), F_LIT(3),  F_LIT(0)},
	{F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(-3), F_LIT(2),
	 F_LIT(0),  F_LIT(3),  F_LIT(-5), F_LIT(0),  F_LIT(-5), F_LIT(2),
	 F_LIT(-2), F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(3),
	 F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(-4), F_LIT(-3), F_LIT(0),
	 F_LIT(-4), F_LIT(3),  F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(3),
	 F_LIT(-2), F_LIT(-3), F_LIT(3),  F_LIT(4),  F_LIT(0),  F_LIT(-4),
	 F_LIT(2),  F_LIT(0),  F_LIT(-2), F_LIT(2),  F_LIT(2),  F_LIT(-4),
	 F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(0),
	 F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(-5), F_LIT(0),  F_LIT(-2),
	 F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-4),
	 F_LIT(-5), F_LIT(3),  F_LIT(3),  F_LIT(3)},
	{F_LIT(-3), F_LIT(-2), F_LIT(-2), F_LIT(-4), F_LIT(4),  F_LIT(0),
	 F_LIT(3),  F_LIT(-2), F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(-5),
	 F_LIT(-2), F_LIT(3),  F_LIT(4),  F_LIT(-5), F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(-3), F_LIT(-3), F_LIT(4),  F_LIT(-5), F_LIT(3),
	 F_LIT(4),  F_LIT(4),  F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(3),  F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(-2), F_LIT(0),
	 F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(-4), F_LIT(0),  F_LIT(3),
	 F_LIT(4),  F_LIT(-4), F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(4),
	 F_LIT(3),  F_LIT(-3), F_LIT(4),  F_LIT(3),  F_LIT(-3), F_LIT(-3),
	 F_LIT(0),  F_LIT(4),  F_LIT(-4), F_LIT(-3), F_LIT(0),  F_LIT(3),
	 F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(0)},
	{F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(-4),
	 F_LIT(4),  F_LIT(-3), F_LIT(4),  F_LIT(-2), F_LIT(0),  F_LIT(0),
	 F_LIT(-2), F_LIT(-3), F_LIT(2),  F_LIT(0),  F_LIT(-4), F_LIT(-4),
	 F_LIT(-3), F_LIT(0),  F_LIT(-3), F_LIT(-2), F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(-3), F_LIT(2),  F_LIT(0),  F_LIT(-4), F_LIT(-3),
	 F_LIT(4),  F_LIT(4),  F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(2),
	 F_LIT(0),  F_LIT(-4), F_LIT(-3), F_LIT(-2), F_LIT(3),  F_LIT(-4),
	 F_LIT(0),  F_LIT(0),  F_LIT(3),  F_LIT(-3), F_LIT(-3), F_LIT(-3),
	 F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(-2), F_LIT(-5), F_LIT(-3),
	 F_LIT(4),  F_LIT(-2), F_LIT(-3), F_LIT(-5), F_LIT(-2), F_LIT(0),
	 F_LIT(-5), F_LIT(-3), F_LIT(0),  F_LIT(-4)},
	{F_LIT(-3), F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(0),
	 F_LIT(3),  F_LIT(3),  F_LIT(3),  F_LIT(4),  F_LIT(3),  F_LIT(0),
	 F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(-4), F_LIT(-5), F_LIT(-4),
	 F_LIT(-5), F_LIT(-3), F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(2),  F_LIT(2),  F_LIT(4),  F_LIT(2),  F_LIT(-5), F_LIT(-5),
	 F_LIT(0),  F_LIT(4),  F_LIT(-3), F_LIT(0),  F_LIT(-5), F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(-2), F_LIT(-4), F_LIT(3),  F_LIT(0),
	 F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(-5), F_LIT(-4),
	 F_LIT(0),  F_LIT(-2), F_LIT(4),  F_LIT(0),  F_LIT(-3), F_LIT(4),
	 F_LIT(-2), F_LIT(-3), F_LIT(2),  F_LIT(0),  F_LIT(-3), F_LIT(4),
	 F_LIT(-3), F_LIT(0),  F_LIT(2),  F_LIT(3)},
	{F_LIT(-5), F_LIT(-5), F_LIT(-2), F_LIT(2),  F_LIT(-5), F_LIT(-5), F_LIT(4),
	 F_LIT(-2), F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(-5), F_LIT(2),  F_LIT(2),
	 F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(3),  F_LIT(-3), F_LIT(0),  F_LIT(0),
	 F_LIT(-3), F_LIT(4),  F_LIT(2),  F_LIT(-3), F_LIT(3),  F_LIT(0),  F_LIT(4),
	 F_LIT(2),  F_LIT(-3), F_LIT(-2), F_LIT(-2), F_LIT(-2), F_LIT(0),  F_LIT(0),
	 F_LIT(-4), F_LIT(-4), F_LIT(4),  F_LIT(-3), F_LIT(-5), F_LIT(-2), F_LIT(2),
	 F_LIT(-4), F_LIT(4),  F_LIT(4),  F_LIT(2),  F_LIT(-4), F_LIT(4),  F_LIT(0),
	 F_LIT(3),  F_LIT(2),  F_LIT(4),  F_LIT(-5), F_LIT(0),  F_LIT(2),  F_LIT(0),
	 F_LIT(-3), F_LIT(-4), F_LIT(4),  F_LIT(-4), F_LIT(-4), F_LIT(0),  F_LIT(0),
	 F_LIT(0)},
	{F_LIT(-2), F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(0),
	 F_LIT(0),  F_LIT(-2), F_LIT(-5), F_LIT(0),  F_LIT(2),  F_LIT(0),
	 F_LIT(-2), F_LIT(-5), F_LIT(3),  F_LIT(2),  F_LIT(0),  F_LIT(3),
	 F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(-2), F_LIT(-4), F_LIT(2),
	 F_LIT(0),  F_LIT(3),  F_LIT(3),  F_LIT(4),  F_LIT(4),  F_LIT(2),
	 F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(0),
	 F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(3),  F_LIT(3),  F_LIT(2),
	 F_LIT(-2), F_LIT(2),  F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(0),
	 F_LIT(-4), F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(-3),
	 F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-3), F_LIT(0),
	 F_LIT(3),  F_LIT(4),  F_LIT(-4), F_LIT(0)},
	{F_LIT(-5), F_LIT(-5), F_LIT(2),  F_LIT(-4), F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(-2), F_LIT(0),  F_LIT(-3), F_LIT(2),  F_LIT(-3),
	 F_LIT(0),  F_LIT(2),  F_LIT(4),  F_LIT(-5), F_LIT(2),  F_LIT(4),
	 F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(4),  F_LIT(3),  F_LIT(2),
	 F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(-3), F_LIT(-3), F_LIT(-2),
	 F_LIT(2),  F_LIT(0),  F_LIT(-4), F_LIT(-5), F_LIT(-3), F_LIT(0),
	 F_LIT(-5), F_LIT(0),  F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(-5),
	 F_LIT(0),  F_LIT(-3), F_LIT(-2), F_LIT(0),  F_LIT(-2), F_LIT(4),
	 F_LIT(4),  F_LIT(3),  F_LIT(-4), F_LIT(0),  F_LIT(-2), F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(-4), F_LIT(-4)},
	{F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(-5),
	 F_LIT(-3), F_LIT(4),  F_LIT(3),  F_LIT(2),  F_LIT(0),  F_LIT(-5),
	 F_LIT(4),  F_LIT(-4), F_LIT(4),  F_LIT(-4), F_LIT(-4), F_LIT(4),
	 F_LIT(4),  F_LIT(-4), F_LIT(-4), F_LIT(-2), F_LIT(-4), F_LIT(-3),
	 F_LIT(-2), F_LIT(0),  F_LIT(2),  F_LIT(-3), F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(2),  F_LIT(-5), F_LIT(0),
	 F_LIT(4),  F_LIT(0),  F_LIT(2),  F_LIT(-3), F_LIT(2),  F_LIT(2),
	 F_LIT(-2), F_LIT(3),  F_LIT(2),  F_LIT(0),  F_LIT(3),  F_LIT(-4),
	 F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(3),  F_LIT(-5), F_LIT(0),
	 F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(-5),
	 F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(0)},
	{F_LIT(-2), F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(-4), F_LIT(0),
	 F_LIT(-3), F_LIT(-3), F_LIT(2),  F_LIT(-3), F_LIT(-5), F_LIT(0),
	 F_LIT(-4), F_LIT(-2), F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(-3),
	 F_LIT(3),  F_LIT(0),  F_LIT(-5), F_LIT(-3), F_LIT(-3), F_LIT(0),
	 F_LIT(2),  F_LIT(2),  F_LIT(3),  F_LIT(-4), F_LIT(4),  F_LIT(3),
	 F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(2),
	 F_LIT(-4), F_LIT(-4), F_LIT(2),  F_LIT(4),  F_LIT(-2), F_LIT(-4),
	 F_LIT(2),  F_LIT(0),  F_LIT(-2), F_LIT(-4), F_LIT(0),  F_LIT(-4),
	 F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(4),  F_LIT(-5), F_LIT(2),
	 F_LIT(4),  F_LIT(2),  F_LIT(4),  F_LIT(0),  F_LIT(2),  F_LIT(0),
	 F_LIT(-4), F_LIT(0),  F_LIT(-4), F_LIT(-2)},
	{F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(3), F_LIT(-4), F_LIT(4),
	 F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(4), F_LIT(0),  F_LIT(-5),
	 F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(0), F_LIT(3),  F_LIT(4),
	 F_LIT(0),  F_LIT(-2), F_LIT(3),  F_LIT(4), F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(-2), F_LIT(-3), F_LIT(0), F_LIT(4),  F_LIT(-4),
	 F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(0), F_LIT(3),  F_LIT(-4),
	 F_LIT(-3), F_LIT(-2), F_LIT(-5), F_LIT(4), F_LIT(2),  F_LIT(2),
	 F_LIT(-4), F_LIT(-2), F_LIT(3),  F_LIT(0), F_LIT(4),  F_LIT(0),
	 F_LIT(3),  F_LIT(-2), F_LIT(-2), F_LIT(4), F_LIT(-2), F_LIT(3),
	 F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(4), F_LIT(0),  F_LIT(0),
	 F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(0)},
	{F_LIT(-4), F_LIT(4),  F_LIT(-4), F_LIT(-5), F_LIT(-5), F_LIT(-2),
	 F_LIT(0),  F_LIT(3),  F_LIT(-5), F_LIT(-2), F_LIT(-2), F_LIT(-2),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(4),  F_LIT(3),
	 F_LIT(4),  F_LIT(-3), F_LIT(0),  F_LIT(3),  F_LIT(4),  F_LIT(-2),
	 F_LIT(0),  F_LIT(4),  F_LIT(-4), F_LIT(3),  F_LIT(3),  F_LIT(2),
	 F_LIT(-2), F_LIT(0),  F_LIT(4),  F_LIT(-2), F_LIT(-5), F_LIT(0),
	 F_LIT(-2), F_LIT(0),  F_LIT(3),  F_LIT(-5), F_LIT(0),  F_LIT(-5),
	 F_LIT(0),  F_LIT(4),  F_LIT(4),  F_LIT(0),  F_LIT(3),  F_LIT(3),
	 F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-4), F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(-3), F_LIT(0),
	 F_LIT(0),  F_LIT(3),  F_LIT(-5), F_LIT(0)},
	{F_LIT(-2), F_LIT(-4), F_LIT(4),  F_LIT(-3), F_LIT(3),  F_LIT(-2),
	 F_LIT(3),  F_LIT(-5), F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(4),
	 F_LIT(0),  F_LIT(-5), F_LIT(4),  F_LIT(-2), F_LIT(-3), F_LIT(0),
	 F_LIT(4),  F_LIT(0),  F_LIT(-4), F_LIT(-4), F_LIT(0),  F_LIT(2),
	 F_LIT(2),  F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(-5), F_LIT(-3),
	 F_LIT(0),  F_LIT(-5), F_LIT(-5), F_LIT(-5), F_LIT(2),  F_LIT(0),
	 F_LIT(0),  F_LIT(-5), F_LIT(4),  F_LIT(-3), F_LIT(4),  F_LIT(-3),
	 F_LIT(-5), F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-5),
	 F_LIT(3),  F_LIT(2),  F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(0),
	 F_LIT(0),  F_LIT(-4), F_LIT(3),  F_LIT(-4), F_LIT(-3), F_LIT(-4),
	 F_LIT(2),  F_LIT(-3), F_LIT(-5), F_LIT(0)},
	{F_LIT(-5), F_LIT(-3), F_LIT(-3), F_LIT(-5), F_LIT(3),  F_LIT(-2),
	 F_LIT(0),  F_LIT(3),  F_LIT(-2), F_LIT(0),  F_LIT(3),  F_LIT(3),
	 F_LIT(0),  F_LIT(-2), F_LIT(-4), F_LIT(-3), F_LIT(2),  F_LIT(3),
	 F_LIT(-3), F_LIT(3),  F_LIT(3),  F_LIT(4),  F_LIT(0),  F_LIT(0),
	 F_LIT(-4), F_LIT(-2), F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(4),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(-3),
	 F_LIT(-5), F_LIT(3),  F_LIT(0),  F_LIT(4),  F_LIT(-4), F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(-5), F_LIT(2),  F_LIT(0),  F_LIT(-3),
	 F_LIT(-3), F_LIT(2),  F_LIT(-3), F_LIT(-2), F_LIT(0),  F_LIT(-2),
	 F_LIT(3),  F_LIT(-3), F_LIT(-5), F_LIT(0),  F_LIT(-5), F_LIT(-3),
	 F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(2)},
	{F_LIT(4),  F_LIT(4),  F_LIT(-2), F_LIT(2),  F_LIT(0), F_LIT(-2), F_LIT(-5),
	 F_LIT(4),  F_LIT(0),  F_LIT(-4), F_LIT(4),  F_LIT(3), F_LIT(2),  F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(0), F_LIT(2),  F_LIT(-3),
	 F_LIT(-4), F_LIT(-3), F_LIT(2),  F_LIT(0),  F_LIT(0), F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(-5), F_LIT(2),  F_LIT(2),  F_LIT(4), F_LIT(-5), F_LIT(4),
	 F_LIT(-5), F_LIT(0),  F_LIT(-2), F_LIT(-5), F_LIT(0), F_LIT(-4), F_LIT(-3),
	 F_LIT(-2), F_LIT(-5), F_LIT(-4), F_LIT(-3), F_LIT(2), F_LIT(0),  F_LIT(-3),
	 F_LIT(2),  F_LIT(0),  F_LIT(-3), F_LIT(0),  F_LIT(0), F_LIT(-2), F_LIT(0),
	 F_LIT(0),  F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(2), F_LIT(0),  F_LIT(-4),
	 F_LIT(2)},
	{F_LIT(-5), F_LIT(-5), F_LIT(4),  F_LIT(4),  F_LIT(-3), F_LIT(-2),
	 F_LIT(-5), F_LIT(0),  F_LIT(-2), F_LIT(2),  F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(-2), F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-3), F_LIT(0),  F_LIT(4),  F_LIT(-4), F_LIT(-3), F_LIT(-5),
	 F_LIT(2),  F_LIT(3),  F_LIT(0),  F_LIT(-3), F_LIT(-5), F_LIT(-4),
	 F_LIT(-4), F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(-3), F_LIT(-5),
	 F_LIT(-5), F_LIT(4),  F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(3),
	 F_LIT(-3), F_LIT(2),  F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(-3),
	 F_LIT(2),  F_LIT(-2), F_LIT(-4), F_LIT(0),  F_LIT(-2), F_LIT(2),
	 F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(3),
	 F_LIT(-5), F_LIT(-3), F_LIT(-3), F_LIT(0)},
	{F_LIT(0),  F_LIT(-2), F_LIT(-4), F_LIT(0),  F_LIT(4),  F_LIT(0),
	 F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(-3), F_LIT(2),
	 F_LIT(0),  F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(-4), F_LIT(-2), F_LIT(4),
	 F_LIT(-5), F_LIT(4),  F_LIT(4),  F_LIT(3),  F_LIT(-3), F_LIT(0),
	 F_LIT(0),  F_LIT(-4), F_LIT(-2), F_LIT(3),  F_LIT(0),  F_LIT(2),
	 F_LIT(-4), F_LIT(-5), F_LIT(-5), F_LIT(0),  F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(-2), F_LIT(-2), F_LIT(0),  F_LIT(-2), F_LIT(0),
	 F_LIT(-5), F_LIT(-2), F_LIT(-5), F_LIT(-5), F_LIT(0),  F_LIT(-2),
	 F_LIT(-4), F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(-4), F_LIT(4),
	 F_LIT(0),  F_LIT(-5), F_LIT(-5), F_LIT(-4)},
	{F_LIT(0),  F_LIT(-2), F_LIT(-2), F_LIT(3),  F_LIT(0),  F_LIT(0),
	 F_LIT(-2), F_LIT(0),  F_LIT(-2), F_LIT(0),  F_LIT(-2), F_LIT(-4),
	 F_LIT(0),  F_LIT(2),  F_LIT(3),  F_LIT(0),  F_LIT(2),  F_LIT(-5),
	 F_LIT(2),  F_LIT(3),  F_LIT(3),  F_LIT(-4), F_LIT(-4), F_LIT(-4),
	 F_LIT(-2), F_LIT(2),  F_LIT(0),  F_LIT(-4), F_LIT(3),  F_LIT(4),
	 F_LIT(3),  F_LIT(-3), F_LIT(4),  F_LIT(0),  F_LIT(-4), F_LIT(2),
	 F_LIT(0),  F_LIT(2),  F_LIT(-3), F_LIT(3),  F_LIT(4),  F_LIT(-5),
	 F_LIT(2),  F_LIT(2),  F_LIT(-3), F_LIT(0),  F_LIT(4),  F_LIT(-2),
	 F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(0),  F_LIT(0),
	 F_LIT(-4), F_LIT(4),  F_LIT(-2), F_LIT(0),  F_LIT(-4), F_LIT(-5),
	 F_LIT(-4), F_LIT(-4), F_LIT(-2), F_LIT(-3)},
	{F_LIT(0),  F_LIT(-3), F_LIT(-2), F_LIT(3),  F_LIT(-5), F_LIT(-3),
	 F_LIT(4),  F_LIT(2),  F_LIT(-5), F_LIT(-3), F_LIT(0),  F_LIT(-2),
	 F_LIT(0),  F_LIT(4),  F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(0),
	 F_LIT(4),  F_LIT(-4), F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(-5),
	 F_LIT(-2), F_LIT(0),  F_LIT(-2), F_LIT(-4), F_LIT(0),  F_LIT(-5),
	 F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(2),  F_LIT(-4), F_LIT(-4),
	 F_LIT(3),  F_LIT(3),  F_LIT(-3), F_LIT(0),  F_LIT(-5), F_LIT(0),
	 F_LIT(3),  F_LIT(0),  F_LIT(-5), F_LIT(4),  F_LIT(-5), F_LIT(2),
	 F_LIT(0),  F_LIT(-2), F_LIT(-4), F_LIT(-5), F_LIT(-4), F_LIT(-2),
	 F_LIT(0),  F_LIT(-5), F_LIT(4),  F_LIT(-4), F_LIT(0),  F_LIT(-3),
	 F_LIT(0),  F_LIT(3),  F_LIT(0),  F_LIT(-2)},
	{F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(3),  F_LIT(2), F_LIT(-5), F_LIT(-5),
	 F_LIT(3),  F_LIT(2),  F_LIT(-3), F_LIT(-4), F_LIT(2), F_LIT(3),  F_LIT(0),
	 F_LIT(0),  F_LIT(-3), F_LIT(3),  F_LIT(-3), F_LIT(4), F_LIT(4),  F_LIT(0),
	 F_LIT(0),  F_LIT(-3), F_LIT(-4), F_LIT(4),  F_LIT(2), F_LIT(-2), F_LIT(3),
	 F_LIT(-4), F_LIT(0),  F_LIT(-4), F_LIT(4),  F_LIT(2), F_LIT(-3), F_LIT(-3),
	 F_LIT(-3), F_LIT(-3), F_LIT(4),  F_LIT(-5), F_LIT(0), F_LIT(-4), F_LIT(0),
	 F_LIT(-5), F_LIT(-5), F_LIT(3),  F_LIT(-5), F_LIT(0), F_LIT(-3), F_LIT(0),
	 F_LIT(4),  F_LIT(-2), F_LIT(3),  F_LIT(-4), F_LIT(0), F_LIT(-3), F_LIT(0),
	 F_LIT(2),  F_LIT(3),  F_LIT(0),  F_LIT(0),  F_LIT(0), F_LIT(-4), F_LIT(-3),
	 F_LIT(2)},
	{F_LIT(-5), F_LIT(-4), F_LIT(0),  F_LIT(4),  F_LIT(4),  F_LIT(-2),
	 F_LIT(3),  F_LIT(0),  F_LIT(-3), F_LIT(-3), F_LIT(-2), F_LIT(-5),
	 F_LIT(2),  F_LIT(4),  F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(2),
	 F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(4),  F_LIT(-5), F_LIT(-4),
	 F_LIT(4),  F_LIT(3),  F_LIT(-3), F_LIT(4),  F_LIT(-4), F_LIT(-3),
	 F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(-4), F_LIT(-5), F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(-2), F_LIT(-3),
	 F_LIT(4),  F_LIT(0),  F_LIT(-4), F_LIT(-2), F_LIT(-2), F_LIT(2),
	 F_LIT(-5), F_LIT(4),  F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(2),
	 F_LIT(-3), F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(2),
	 F_LIT(0),  F_LIT(2),  F_LIT(-4), F_LIT(2)},
	{F_LIT(-3), F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(2),  F_LIT(4),
	 F_LIT(3),  F_LIT(-2), F_LIT(-5), F_LIT(2),  F_LIT(0),  F_LIT(0),
	 F_LIT(-3), F_LIT(-4), F_LIT(4),  F_LIT(0),  F_LIT(-5), F_LIT(3),
	 F_LIT(4),  F_LIT(-3), F_LIT(-2), F_LIT(-3), F_LIT(-4), F_LIT(3),
	 F_LIT(0),  F_LIT(-5), F_LIT(-5), F_LIT(-4), F_LIT(-2), F_LIT(-3),
	 F_LIT(-4), F_LIT(4),  F_LIT(-4), F_LIT(-4), F_LIT(-3), F_LIT(0),
	 F_LIT(-5), F_LIT(0),  F_LIT(-4), F_LIT(-2), F_LIT(-2), F_LIT(2),
	 F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(4),  F_LIT(0),
	 F_LIT(-5), F_LIT(-5), F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(4),
	 F_LIT(0),  F_LIT(-4), F_LIT(-5), F_LIT(-3), F_LIT(-4), F_LIT(-4),
	 F_LIT(2),  F_LIT(4),  F_LIT(0),  F_LIT(4)},
	{F_LIT(-4), F_LIT(-3), F_LIT(0),  F_LIT(-2), F_LIT(-5), F_LIT(-5),
	 F_LIT(3),  F_LIT(0),  F_LIT(-2), F_LIT(-5), F_LIT(4),  F_LIT(2),
	 F_LIT(4),  F_LIT(-5), F_LIT(0),  F_LIT(0),  F_LIT(2),  F_LIT(4),
	 F_LIT(4),  F_LIT(4),  F_LIT(3),  F_LIT(-4), F_LIT(2),  F_LIT(-2),
	 F_LIT(-4), F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(0),  F_LIT(0),
	 F_LIT(-3), F_LIT(0),  F_LIT(-3), F_LIT(2),  F_LIT(0),  F_LIT(2),
	 F_LIT(0),  F_LIT(4),  F_LIT(-4), F_LIT(0),  F_LIT(2),  F_LIT(0),
	 F_LIT(3),  F_LIT(0),  F_LIT(3),  F_LIT(-3), F_LIT(0),  F_LIT(-5),
	 F_LIT(4),  F_LIT(-5), F_LIT(3),  F_LIT(-5), F_LIT(-5), F_LIT(2),
	 F_LIT(0),  F_LIT(-2), F_LIT(-3), F_LIT(4),  F_LIT(-2), F_LIT(-3),
	 F_LIT(0),  F_LIT(0),  F_LIT(-5), F_LIT(0)},
	{F_LIT(3),  F_LIT(-2), F_LIT(3),  F_LIT(-3), F_LIT(0),  F_LIT(-2),
	 F_LIT(-3), F_LIT(-2), F_LIT(3),  F_LIT(2),  F_LIT(2),  F_LIT(3),
	 F_LIT(-2), F_LIT(3),  F_LIT(0),  F_LIT(-5), F_LIT(-5), F_LIT(0),
	 F_LIT(-3), F_LIT(3),  F_LIT(-3), F_LIT(2),  F_LIT(-2), F_LIT(-5),
	 F_LIT(-4), F_LIT(2),  F_LIT(2),  F_LIT(-5), F_LIT(0),  F_LIT(0),
	 F_LIT(-5), F_LIT(4),  F_LIT(-2), F_LIT(4),  F_LIT(4),  F_LIT(2),
	 F_LIT(-4), F_LIT(4),  F_LIT(-2), F_LIT(0),  F_LIT(2),  F_LIT(3),
	 F_LIT(2),  F_LIT(-3), F_LIT(2),  F_LIT(-3), F_LIT(-4), F_LIT(2),
	 F_LIT(2),  F_LIT(-4), F_LIT(-2), F_LIT(0),  F_LIT(-5), F_LIT(-5),
	 F_LIT(-4), F_LIT(4),  F_LIT(0),  F_LIT(-5), F_LIT(-3), F_LIT(3),
	 F_LIT(4),  F_LIT(2),  F_LIT(3),  F_LIT(-3)},
	{F_LIT(0),  F_LIT(4),  F_LIT(-3), F_LIT(4),  F_LIT(2),  F_LIT(4),
	 F_LIT(0),  F_LIT(3),  F_LIT(-4), F_LIT(-3), F_LIT(4),  F_LIT(3),
	 F_LIT(-5), F_LIT(3),  F_LIT(-4), F_LIT(0),  F_LIT(-3), F_LIT(0),
	 F_LIT(2),  F_LIT(0),  F_LIT(2),  F_LIT(0),  F_LIT(3),  F_LIT(2),
	 F_LIT(0),  F_LIT(-3), F_LIT(4),  F_LIT(-2), F_LIT(3),  F_LIT(3),
	 F_LIT(-5), F_LIT(-5), F_LIT(3),  F_LIT(4),  F_LIT(0),  F_LIT(3),
	 F_LIT(3),  F_LIT(-3), F_LIT(-2), F_LIT(-4), F_LIT(4),  F_LIT(-3),
	 F_LIT(-2), F_LIT(4),  F_LIT(0),  F_LIT(-2), F_LIT(-4), F_LIT(2),
	 F_LIT(3),  F_LIT(2),  F_LIT(-5), F_LIT(0),  F_LIT(2),  F_LIT(0),
	 F_LIT(-4), F_LIT(-4), F_LIT(-4), F_LIT(-5), F_LIT(3),  F_LIT(-2),
	 F_LIT(-5), F_LIT(0),  F_LIT(-3), F_LIT(-4)}};

#endif