# The index of the UART module And its pins (e.g. '1.5')
LIBMSPUARTLINK_UART_IDX ?=
LIBMSPUARTLINK_PIN_RX ?= 
LIBMSPUARTLINK_PIN_TX ?= 

# Baudrate to configure the UART to
LIBMSPUARTLINK_BAUDRATE ?= 115200

# Clock source for UART
LIBMSPUARTLINK_CLOCK ?= SMCLK
